# Generated by Django 5.0.7 on 2025-10-16 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_paymentorder_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone_verified',
        ),
    ]
